### PR TITLE
File download bug

### LINKED ISSUE #24: FileDownload State is not completely set
We should update the minRange to be equal to maxRange in db when the download is completed. And in the constructor we should check and set the correct state and notify UI so that it can correctly show the right state. It must also be added to availables table also once the download is complete

### PR DESCRIPTION
**Pull request by kss682**
Fixes #24 .

### CODE REVIEW

File: app/src/main/java/com/nevilleantony/prototype/downloadmanager/DownloadRepo.java [hunk 1]
```diff
@@ -145,6 +145,10 @@ public void updateMinRange(String groupId, Long range, Long minRange) {
         stgApi.updateMinRange(groupId, range, minRange);
     }
 
+    public void insertAvailDownloads(String groupId, Long partNo){
+        stgApi.insertAvailDownload(groupId, partNo);
+    }
+
```
Comment (NevilleAntony98) [inline app/src/main/java/com/nevilleantony/prototype/downloadmanager/DownloadRepo.java]: 1) This method should also update the `availablePartsMap`
2) There is already a method for this, see `addAvailablePart`, so is not needed

**Review by NevilleAntony98 — CHANGES_REQUESTED** [review]

**Review by NevilleAntony98 — APPROVED** [review]
